uploads = []
generated = []

[[outputs]]
id = "_VMH8i1Kju0lZovB3lRKd"
uri = "file://tr-agency-source.tar.gz"
type = "unspecified"
title = "T/R Agency — Full Source Code"

[[outputs]]
id = "1bmhczTumiD7ZQO1dhedQ"
uri = "file://tr-agency-source.zip"
type = "unspecified"
title = "T/R Agency — Full Source Code (.zip)"

[[outputs]]
id = "WUQTgcyjvFx4_A7-jvVmE"
uri = "file://tr-agency-github.zip"
type = "unspecified"
title = "T/R Agency — Full Source Code (GitHub Ready)"
