import express from "express";
import cors from "cors";
import session from "express-session";
import MemoryStore from "memorystore";
import path from "path";
import { fileURLToPath } from "url";
import authRoutes from "./routes/auth.js";
import projectRoutes from "./routes/projects.js";
import passportInstance from "./passport.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const isProd = process.env.NODE_ENV === "production";
const PORT = process.env.PORT || (isProd ? 5000 : 3001);

// ── CORS ──────────────────────────────────────────────────────────────────────
const FRONTEND_ORIGIN = process.env.FRONTEND_URL
  ? process.env.FRONTEND_URL.trim().replace(/\/$/, "")
  : null;

app.use(
  cors({
    origin: FRONTEND_ORIGIN
      ? (origin, cb) => {
          if (!origin || origin === FRONTEND_ORIGIN) return cb(null, true);
          return cb(null, false);
        }
      : true,
    credentials: true,
    allowedHeaders: ["Content-Type", "Authorization", "x-admin-key"],
    methods: ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"],
  })
);

// ── Body size limits ──────────────────────────────────────────────────────────
app.use(express.json({ limit: "20mb" }));
app.use(express.urlencoded({ extended: true, limit: "20mb" }));

// ── Server-side project initialization webhook ───────────────────────────────
// Capture the ACTUAL project returned by POST /api/projects. The project ID is
// generated by the backend, so req.body cannot contain it.
app.use((req, res, next) => {
  if (req.method !== "POST" || req.path !== "/api/projects") return next();

  const originalJson = res.json.bind(res);

  res.json = (body) => {
    if (res.statusCode === 201 && body?.ok && body?.project) {
      const webhookUrl = process.env.VITE_DISCORD_WEBHOOK_URL || "";

      if (!webhookUrl) {
        console.warn("[project-init-webhook] VITE_DISCORD_WEBHOOK_URL is not configured");
      } else {
        const project = body.project;
        const projectId = project.id || "—";
        const submittedAt = project.submittedAt || new Date().toISOString();

        fetch(webhookUrl, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({
            username: "T/R Intake — System",
            content: "**New Project Initialized** — admin-leads",
            embeds: [
              {
                title: `🚀 Project Initialized — ${project.service || "General Consult"}`,
                color: 0x38bdf8,
                fields: [
                  { name: "Project ID", value: String(projectId), inline: true },
                  { name: "Name", value: project.name || "—", inline: true },
                  { name: "Email", value: project.email || "—", inline: true },
                  { name: "Project URL", value: project.projectUrl || "—", inline: true },
                  { name: "Project Type", value: project.projectType || "—", inline: true },
                  { name: "Current Stage", value: project.stage || "—", inline: true },
                  { name: "Referral Source", value: project.referralSource || "—", inline: true },
                  ...(project.promoterCode
                    ? [{ name: "Promoter Code", value: String(project.promoterCode), inline: true }]
                    : []),
                  { name: "Service", value: project.service || "General Consult", inline: false },
                  { name: "Main Issue / Goal", value: project.mainIssue || "—", inline: false },
                ],
                footer: { text: "T/R Agency · Project Initialization" },
                timestamp: submittedAt,
              },
            ],
          }),
        })
          .then(async (webhookResponse) => {
            if (!webhookResponse.ok) {
              const text = await webhookResponse.text().catch(() => "");
              console.error(
                `[project-init-webhook] Discord returned ${webhookResponse.status}: ${text}`
              );
              return;
            }
            console.log(`[project-init-webhook] Notification sent for ${projectId}`);
          })
          .catch((err) => {
            console.error("[project-init-webhook] Failed to send:", err);
          });
      }
    }

    return originalJson(body);
  };

  next();
});

// ── Session (used only for OAuth state — max 10 min) ─────────────────────────
const SessionStore = MemoryStore(session);
app.use(
  session({
    store: new SessionStore({
      checkPeriod: 10 * 60 * 1000,
    }),
    secret: process.env.SESSION_SECRET || "dev-fallback-secret-change-in-production",
    resave: false,
    saveUninitialized: false,
    cookie: {
      secure: isProd,
      httpOnly: true,
      maxAge: 10 * 60 * 1000,
    },
  })
);

// ── Passport (OAuth strategies) ───────────────────────────────────────────────
app.use(passportInstance.initialize());
app.use(passportInstance.session());

// ── Security headers ──────────────────────────────────────────────────────────
app.use((_req, res, next) => {
  res.setHeader("X-Content-Type-Options", "nosniff");
  res.setHeader("X-Frame-Options", "DENY");
  res.setHeader("X-XSS-Protection", "1; mode=block");
  res.setHeader("Referrer-Policy", "strict-origin-when-cross-origin");
  next();
});

// ── Request logger (dev only) ─────────────────────────────────────────────────
if (!isProd) {
  app.use((req, _res, next) => {
    const size = req.headers["content-length"]
      ? `(${(parseInt(req.headers["content-length"]) / 1024).toFixed(1)}kb)`
      : "";
    console.log(`[${new Date().toISOString()}] ${req.method} ${req.path} ${size}`);
    next();
  });
}

// ── Health check ──────────────────────────────────────────────────────────────
app.get("/api/health", (_req, res) => {
  res.json({
    ok: true,
    status: "operational",
    env: isProd ? "production" : "development",
    uptime: Math.floor(process.uptime()),
    timestamp: new Date().toISOString(),
  });
});

// ── API routes ────────────────────────────────────────────────────────────────
app.use("/api/auth", authRoutes);
app.use("/api/projects", projectRoutes);

// ── API 404 handler (Express 5 safe) ─────────────────────────────────────────
app.use("/api", (_req, res) => {
  res.status(404).json({ ok: false, error: "API route not found." });
});

// ── Global error handler ──────────────────────────────────────────────────────
app.use((err, _req, res, _next) => {
  console.error("[ERROR]", err.message, err.stack);
  if (err.type === "entity.too.large") {
    return res.status(413).json({ ok: false, error: "File too large. Maximum size is 20MB." });
  }
  res.status(500).json({ ok: false, error: isProd ? "Internal server error." : err.message });
});

// ── Serve frontend in production ──────────────────────────────────────────────
if (isProd) {
  const DIST = path.join(__dirname, "../dist");
  app.use((req, res, next) => {
    if (/\/(sw\.js|index\.html|manifest\.webmanifest)$/.test(req.path)) {
      res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
      res.setHeader("Pragma", "no-cache");
    }
    next();
  });
  app.use(express.static(DIST, { maxAge: "1d", etag: true }));
  app.use((_req, res) => {
    res.setHeader("Cache-Control", "no-store, no-cache, must-revalidate");
    res.sendFile(path.join(DIST, "index.html"));
  });
}

// ── Keep-alive self-ping ──────────────────────────────────────────────────────
function startKeepAlive() {
  const SELF_URL = (process.env.APP_URL || "").trim().replace(/\/$/, "");
  if (!SELF_URL) {
    console.log("⚠️  [keep-alive] APP_URL not set — self-ping disabled.");
    return;
  }
  const INTERVAL_MS = 10 * 60 * 1000;

  setInterval(() => {
    fetch(`${SELF_URL}/api/health`)
      .then((res) => {
        const ts = new Date().toISOString();
        console.log(`💓 [keep-alive] ${ts} — ping ok (${res.status})`);
      })
      .catch((err) => {
        const ts = new Date().toISOString();
        console.error(`⚠️  [keep-alive] ${ts} — ping failed: ${err.message}`);
      });
  }, INTERVAL_MS);

  console.log(`💓 [keep-alive] Armed — pinging self every 10 minutes.`);
}

// ── Start server ──────────────────────────────────────────────────────────────
app.listen(PORT, "0.0.0.0", () => {
  const ts = new Date().toISOString();
  console.log(`\n╔═══════════════════════════════════════════════════╗\n║                                                     ║\n║        ▲ T/R AGENCY — CORE API ▲                   ║\n║        Operational Systems Online                  ║\n║                                                     ║\n╠═══════════════════════════════════════════════════╣\n║  ● Port         : ${String(PORT).padEnd(33)}║\n║  ● Mode         : ${(isProd ? "PRODUCTION" : "DEVELOPMENT").padEnd(33)}║\n║  ● Body limit   : ${"20mb".padEnd(33)}║\n║  ● Boot time    : ${ts.padEnd(33)}║\n║  ● Status       : ${"ALL SYSTEMS NOMINAL".padEnd(33)}║\n║                                                     ║\n╚═══════════════════════════════════════════════════╝\n  `);

  if (isProd) startKeepAlive();
});